DROP TABLE IF EXISTS films CASCADE;

CREATE TABLE films (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) DEFAULT NULL,
  price FLOAT DEFAULT NULL,
  trailer VARCHAR(255) DEFAULT NULL,
  introduction VARCHAR(255) DEFAULT NULL,
  released DATE DEFAULT CURRENT_DATE,
  year VARCHAR(255) DEFAULT NULL,
  customer_id INTEGER REFERENCES users(id),
  category_id INTEGER REFERENCES categories(id)
);