INSERT INTO films (name, trailer, price) VALUES ('The Godfather', 'https://www.youtube.com/embed/UaVTIH8mujA', 20);
INSERT INTO films (name, trailer, price) VALUES ('The Shawshank Redemption', 'https://www.youtube.com/embed/NmzuHjWmXOc', 20);
INSERT INTO films (name, trailer, price) VALUES ('The Godfather Part II', 'https://www.youtube.com/embed/OA1ij0alE0w', 20);
INSERT INTO films (name, trailer, price) VALUES ('puss in boots the last wish trailer', 'https://www.youtube.com/embed/Y5zqweZAEKI', 20);
INSERT INTO films (name, trailer, price) VALUES ('Dilwale Dulhania Le Jayenge', 'https://www.youtube.com/embed/oIZ4U21DRlM', 20);
INSERT INTO films (name, trailer, price) VALUES ('Schindler''s List', 'https://www.youtube.com/embed/mxphAlJID9U', 20);
INSERT INTO films (name, trailer, price) VALUES ('Spirited Away', 'https://www.youtube.com/embed/ByXuk9QqQkk', 20);
INSERT INTO films (name, trailer, price) VALUES ('12 Angry Men', 'https://www.youtube.com/embed/TEN-2uTi2c0', 20);
INSERT INTO films (name, trailer, price) VALUES ('Your Name.', 'https://www.youtube.com/embed/o4-URMnBOPU', 20);
INSERT INTO films (name, trailer, price) VALUES ('Parasite', 'https://www.youtube.com/embed/5xH0HfJHsaY', 20);
INSERT INTO films (name, trailer, price) VALUES ('The Green Mile', 'https://www.youtube.com/embed/Bg7epsq0OIQ', 20);
INSERT INTO films (name, trailer, price) VALUES ('The Dark Knight', 'https://www.youtube.com/embed/EXeTwQWrcwY', 20);
INSERT INTO films (name, trailer, price) VALUES ('Pulp Fiction', 'https://www.youtube.com/embed/tGpTpVyI_OQ', 20);
INSERT INTO films (name, trailer, price) VALUES ('The Good, the Bad and the Ugly', 'https://www.youtube.com/embed/IFNUGzCOQoI', 20);
INSERT INTO films (name, trailer, price) VALUES ('Forrest Gump', 'https://www.youtube.com/embed/XHhAG-YLdk8', 20);
INSERT INTO films (name, trailer, price) VALUES ('Dou kyu sei – Classmates', 'https://www.youtube.com/embed/R8KZ9WOTU78', 20);
INSERT INTO films (name, trailer, price) VALUES ('Gabriel''s Inferno', 'https://www.youtube.com/embed/kgWFjmiqHmQ', 20);
INSERT INTO films (name, trailer, price) VALUES ('The Lord of the Rings: The Return of the King', 'https://www.youtube.com/embed/r5X-hFf6Bwo', 20);
INSERT INTO films (name, trailer, price) VALUES ('GoodFellas', 'https://www.youtube.com/embed/xWMxvFvhAB8', 20);
INSERT INTO films (name, trailer, price) VALUES ('Gabriel''s Inferno: Part II', 'https://www.youtube.com/embed/5g02v1oz5Y0', 20);
INSERT INTO films (name, trailer, price) VALUES ('The Boy, the Mole, the Fox and the Horse', 'https://www.youtube.com/embed/Fbdem4g_LEc', 20);